name: Build Python Version

on: 
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build-win:
    runs-on: windows-2016
    strategy:
      matrix:
        arch: [x64,x86]
        python_version: [3.7,3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        path: robotraconteur
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python_version }}'
        architecture: ${{ matrix.arch }}
    - uses: haya14busa/action-cond@v1
      id: vcpkg_triplet
      with:
        cond: ${{ matrix.arch == 'x86' }}
        if_true: "x86-windows-static-md"
        if_false: "x64-windows-static-md"
    - name: vcpkg
      working-directory: ${{ env.VCPKG_INSTALLATION_ROOT }}
      run: >
        vcpkg install --triplet ${{ steps.vcpkg_triplet.outputs.value }} boost-algorithm boost-array boost-asio 
        boost-assign boost-atomic boost-bind boost-config boost-container boost-date-time 
        boost-smart-ptr boost-filesystem boost-foreach boost-format boost-function boost-interprocess
        boost-intrusive boost-lexical-cast boost-locale boost-random boost-range boost-regex
        boost-scope-exit boost-signals2 boost-thread boost-tuple boost-unordered 
        boost-utility boost-uuid boost-program-options
    - name: pip3
      run: |
        python -m pip install numpy setuptools wheel
    - name: env python3
      run: echo  ("PYTHON3_EXE=" + (Get-Command Python.exe).Path) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: choco
      run: |
        choco install swig -r
    - uses: haya14busa/action-cond@v1
      id: cmake_arch
      with:
        cond: ${{ matrix.arch == 'x86' }}
        if_true: "Win32"
        if_false: "x64"
    - name: configure
      run: >
        md -Force build2 && cd build2 &&
        cmake -G "Visual Studio 15 2017" -A ${{ steps.cmake_arch.outputs.value }} 
        -DBoost_USE_STATIC_LIBS=ON
        -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON        
        -DPYTHON3_EXECUTABLE="${{ env.PYTHON3_EXE }}"
        ("-DCMAKE_TOOLCHAIN_FILE=" + $env:VCPKG_INSTALLATION_ROOT + "/scripts/buildsystems/vcpkg.cmake")
        -DVCPKG_TARGET_TRIPLET=${{ steps.vcpkg_triplet.outputs.value }}
        ../robotraconteur
    - name: build
      run: |
        cd build2
        cmake --build . --config Release -j 4
    - name: test
      run: |
        cd build2
        ctest . -C Release --output-on-failure
    - name: move out
      run: |
        mv build2/out .
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: 'out-win-${{ matrix.arch }}'
        path: out/*

  build-osx:

    runs-on: macos-10.15
    env:
      LIBRARY_PATH: /usr/local/opt/icu4c/lib
    strategy:
      matrix:
        python_version: [3.7,3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        path: robotraconteur
    - name: brew
      run: |
        brew install swig boost openssl
    - uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python_version }}'
        architecture: x64
    - name: pip3
      run: |
        python -m pip install numpy setuptools wheel
    - name: env python3
      run: echo "PYTHON3_EXE=${{ env.pythonLocation }}/bin/python" >> $GITHUB_ENV
    - name: configure
      run: >
        mkdir build2 && cd build2 &&
        cmake -G "Xcode" -DBUILD_GEN=ON  -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON 
        -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release        
        -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
        -DOPENSSL_USE_STATIC_LIBS=ON
        -DPYTHON3_EXECUTABLE="${{ env.PYTHON3_EXE }}"
        ../robotraconteur
    - name: build
      run: |        
        cd build2
        cmake --build . --config Release -j 4
    - name: test
      run: |
        cd build2
        ctest . -C Release --output-on-failure
    - name: move out
      run: |
        mv build2/out .
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: 'out-osx'
        path: out/*
    
      